[package]
name = "plannabot"
version = "0.1.0"
edition = "2021"

[dependencies]
teloxide = { version = "0.17.0", default-features = false, features = ["macros", "rustls", "ctrlc_handler"] }
telluride = { path = ".." }
tokio = { version = "1.8", features = ["fs", "sync", "macros", "rt-multi-thread"] }
log = "0.4"
pretty_env_logger = "0.5"
async-trait = "0.1"

[[bin]]
name = "plannabot"
path = "src/main.rs"
