[package]
name = "plannabot"
version = "0.1.0"
edition = "2024"

[dependencies]
teloxide.workspace = true
telluride = { path = ".." }
tokio.workspace = true
log.workspace = true
pretty_env_logger.workspace = true
async-trait.workspace = true
serde.workspace = true
google-sheets4.workspace = true
reqwest.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
anyhow.workspace = true
serde_json.workspace = true
dotenv.workspace = true
bitcode.workspace = true
paste.workspace = true

[[bin]]
name = "plannabot"
path = "src/main.rs"
